# AUTOGENERATED FROM 'queries/get_user_posts.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid
from typing import cast


@dataclasses.dataclass
class GetUserPostsResult:
    id: uuid.UUID
    posts: list[GetUserPostsResultPostsItem]


@dataclasses.dataclass
class GetUserPostsResultPostsItem:
    id: uuid.UUID
    title: str
    content: str


async def get_user_posts(
    executor: gel.AsyncIOExecutor,
    *,
    skip: int,
    limit: int,
    user_id: uuid.UUID,
) -> GetUserPostsResult | None:
    return cast(GetUserPostsResult | None, await executor.query_single(
        """\
        SELECT User {
            id,
            posts: {
                id,
                title,
                content
            } ORDER BY .id OFFSET <int64>$skip LIMIT <int64>$limit
        }
        FILTER .id = <uuid>$user_id;\
        """,
        skip=skip,
        limit=limit,
        user_id=user_id,
    ))
