# AUTOGENERATED FROM 'queries/get_user.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid
from typing import cast


@dataclasses.dataclass
class GetUserResult:
    id: uuid.UUID
    name: str
    email: str


async def get_user(
    executor: gel.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> GetUserResult | None:
    return cast(GetUserResult | None, await executor.query_single(
        """\
        SELECT User {
            id,
            name,
            email
        }
        FILTER .id = <uuid>$user_id;\
        """,
        user_id=user_id,
    ))
