# AUTOGENERATED FROM 'queries/get_users.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid
from typing import cast


@dataclasses.dataclass
class GetUsersResult:
    id: uuid.UUID
    name: str
    email: str


async def get_users(
    executor: gel.AsyncIOExecutor,
    *,
    skip: int,
    limit: int,
) -> list[GetUsersResult]:
    return cast(list[GetUsersResult], await executor.query(
        """\
        SELECT User {
            id,
            name,
            email
        }
        ORDER BY .id
        OFFSET <int64>$skip
        LIMIT <int64>$limit;\
        """,
        skip=skip,
        limit=limit,
    ))
