# AUTOGENERATED FROM 'queries/create_post.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid
from typing import cast


@dataclasses.dataclass
class CreatePostResult:
    id: uuid.UUID
    title: str
    content: str
    user: CreatePostResultUser


@dataclasses.dataclass
class CreatePostResultUser:
    id: uuid.UUID


async def create_post(
    executor: gel.AsyncIOExecutor,
    *,
    title: str,
    content: str,
    user_id: uuid.UUID,
) -> CreatePostResult:
    return cast(CreatePostResult, await executor.query_single(
        """\
        WITH new_post := (
            INSERT Post {
                title := <str>$title,
                content := <str>$content,
                user := (SELECT User FILTER .id = <uuid>$user_id)
            }
        )
        SELECT new_post {
            id,
            title,
            content,
            user: { id }
        };\
        """,
        title=title,
        content=content,
        user_id=user_id,
    ))
