# AUTOGENERATED FROM 'queries/get_posts.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid
from typing import cast


@dataclasses.dataclass(frozen=True)
class GetPostsResult:
    id: uuid.UUID
    title: str
    content: str
    user: GetPostsResultUser


@dataclasses.dataclass(frozen=True)
class GetPostsResultUser:
    id: uuid.UUID


async def get_posts(
    executor: gel.AsyncIOExecutor,
    *,
    skip: int,
    limit: int,
) -> list[GetPostsResult]:
    return cast(list[GetPostsResult], await executor.query(
        """\
        SELECT Post {
            id,
            title,
            content,
            user: { id }
        }
        ORDER BY .id DESC
        OFFSET <int64>$skip
        LIMIT <int64>$limit;\
        """,
        skip=skip,
        limit=limit,
    ))
